// #2

void main()
{
  // var name="Ayush";
  // print(name);
  // print(name.runtimeType);
  // print("Raj");
  // var a=10;
  // print(a);
  // print(a.runtimeType);
  // var bc=10.60;  //double bc=10.60 is also valid
  // print(bc);
  // print(bc.runtimeType);
  // bool love=true;
  // print(love);
  // print(love.runtimeType);

  //arithmetic operatation
  // var a=10;
  // var b=3;
  // print(a/b);
  // print(a ~/b);

  // ## post and prefix
  // var i=4;
  // print(i);
  // print(i++);
  // print(i);
  // print(++i);
  // print(i);


  // ## Type Test Operator
  // var Love = "Sweta";
  // print(Love is String);
  // print(Love is! int);
  // print(Love is double);

  //n += 5    n=n+5
  //n -= 5
  //n *= 5    n=n*5

  // ##conditional Expression
  // var is_login = false;
  // print(is_login.runtimeType);
  // var user = is_login ? 'Riya' : 'Sahil';
  // print(user);

  // var name1 = 'jay';
  // var name1 = null;
  // var user1 = name1 ?? 'Rina';
  // print(user1);


  // ##String

  // print -> 'It's a ayush  <- is not possible coz of three '
  // var s = 'It\'s a ayush';
  // print(s);

  //var s1 = "It's a ayush";
  //print(s1);

  // var mstr = '''This is
  //Multiline
  //String''';
  //print(mstr);
  //note --> u can also use of """ in place of '''

  // ##Expression inside String;

  // var name = 'aayush';
  // print('My name is ${name}');
  // print('My name is ${name.toUpperCase()}');
  // var name2 = 'SWETA';
  // var city = 'Surat';
  // print('Her name is ${name2} and she is good girl. She live in ${city}.');
  // print('Her name is ${name2.toLowerCase()}');


  // ## String Concatenation

  //print('Hello' + ' ' + "Sweta");   //Like JAVA add two string s1 + s2

  //  ##Raw String ---->  no effect of \n,\t,....etc.
  // syntax ----->   var str = r'......msg......';

  // var str = 'hello \nDart';
  // var str1 = r'hello \n Dart';
  // print(str);
  // print(str1);

  // var name = 'Aayush';
  // print(name.length);
  // print(name.isNotEmpty);
  // print(name.isEmpty);
  // print(name.contains('a'));
  // print(name.padLeft(10));
  // print(name.padRight(10));
  // var str = '       hello       ';
  // print(str);
  // print(str.trim());
  // print(str.trimRight());
  // print(str.trimLeft());
  // var str1 = 'Hello my name is ayush ginoya';
  // print(str1.split(' '));
  // var str2 = 'sahil&riya';
  // print(str2.split('&'));
  
}