//   #3

void main()
{
  //## fixed Length list

  // var lst1 = List.filled(5,null);
  // var lst2 = List.filled(5,int);
  // var lst3 = List.filled(5,true);
  // var lst4 = List.filled(5,String);
  // //List<String> ls = new List(3);
  // print(lst1);
  // print(lst2);
  // print(lst3);
  // print(lst4);
  // print(lst1.runtimeType);
  // print(lst2.runtimeType);
  // print(lst3.runtimeType);
  // print(lst4.runtimeType);


  //List<String> lst = new List(3);   ---> default List constructor.

  // ## Growable List

  // var lst = ["Raj","Deep","Sahil","Vansh","Ayush",10];
  // // String + int = object
  // // int + double = object
  // // int = int
  // // String = String
  // // double = double
  // print(lst);
  // print(lst.runtimeType);
  // print(lst[0]);
  // print(lst[1]);
  // print(lst[2]);
  // print(lst[3]);
  // print(lst[4]);
  // print(lst[5]);


  // // if want to insert only String or int then use <String> or <int> 


  // var lst1 = <String>["Raj","Deep","Sahil","Vansh","Ayush"];
  // print(lst1);

  // var lst2 = <int>[5,10,15,20,25,30];
  // print(lst2);

  // ##Insert list into another list
  // spread Operator

  // var girl = ["Sweta","Shruti","Rinu","Aarya","Arzoo"];
  // var boy = ["Ayush","Deep","Raj","Sahil","Yaksh"];
  // var city = ["Rajkot","Surat", ...girl,...boy];
  // var people = [...girl,...boy];
  // print(people);
  // print(city);


  // ## Empty List and add() method

  // var stud = new List();
  // stud.add("Ayush");
  // stud.add("Ayush");
  // stud.add("Ayush");
  // print(stud.runtimeType);
  // print(stud);

  // var stud = [];
  // print(stud);
  // stud.add("Ayush");
  // stud.add("Ayushi");
  // stud.add("Aayush");
  // print(stud.runtimeType);
  // print(stud);

  // ## List Properties and Method

//  var name = ["Sweta","Ayush","Nikhil","Zenisha","Shruti","Raj","Deep"];
//  print(name);
//  print(name.length);
//  print(name.isEmpty);
//  print(name.isNotEmpty);
//  print(name.reversed);
//  print(name.first);
//  print(name.last);
//  name.remove("Nikhil");
//  print(name);
//  name.removeAt(5);
//  print(name);
//  name.removeLast();
//  print(name);

 
}