// ##4

void main()
{
  // var s={"Ayush","Deep","Sahil","Raj","Vansh"};
  // print(s);
  // print(s.runtimeType);

  // var s1={"Ayush","Deep","Sahil","Raj","Vansh",1,2,3,4};
  // print(s1);
  // print(s1.runtimeType);

  // var s2=<String>{"Ayush","Deep","Sahil","Raj","Vansh"};
  // print(s2);
  // print(s2.runtimeType);

  // Set<String> s3 = {"Ayush","Deep","Sahil","Raj","Vansh"};
  // print(s3);
  // print(s3.runtimeType);

  
  // ##Empty Set

  // var s4=<String>{};
  // print(s4);
  // print(s4.runtimeType);

  // var s5={};
  // print(s5);
  // print(s5.runtimeType);

  // //if we not use <> beside {},then set becam map

  // Set<String> s6=Set();
  // print(s6);
  // print(s6.runtimeType);



  //  ## add item into empty set
   
    // Set<String> p=Set();
    // p.add("JAVA");
    // p.add("C++");
    // p.add("Dart");
    // p.add("HTML");
    // print(p);

  // var a= {1,2,3,4,2,1,3,4,6};
  // print(a); 

  //no duplicate value will be concider
}