//  ##7


void main()
{
  // fun()
  // {
  //   int a=10;
  //   int b=20;
  //   return a+b;
  // }
  // print(fun());


  // fun(a,b)
  // {
  //   return a+b;
  // }
  // print(fun(50,32));

  // fun(int a,int b)
  // {
  //   return a+b;
  // }
  // print(fun(50,32));


  //###Optional Positional Perameter

  // String fun(String name,[String city])
  // {
  //   return 'I am $name from $city';
  // }
  // print(fun('Ayush'));


  //  ###Defult parameter

  // String fun(String name,[String city = 'Jamnagar'])
  // {
  //   return 'I am $name from $city';
  // }
  // print(fun('Ayush'));

  // String fun1(String name,[String city = 'Jamnagar'])
  // {
  //   return 'I am $name from $city';
  // }
  // var r=fun1('Ayush','Rajkot');
  // print(r);


  //Named parameter


    // fun({a,b})        //({int a,int b})   ----> not valid.
    // {
    //   print('a = ${a}');
    //   print('b = ${b}');
    // }
    // fun(b:364, a:3);


    // fun(x,{a,b})
    // {
    //   print('a=${a} & b=${b} & name=${x}');
    // }

    // fun('ayush',a:50,b:28);



    //   ####Anonymous Function

    // var lst = ["Raj","Deep","Sahil","Vansh","Ayush"];
    // lst.forEach((value) {
    //   print(value);
    // });
}