//   ##6

void main()
{
  //  ##for in loop with Set

  // var student = {'raj','hddj','skla','maskj'};
  // for(var st in student)
  // {
  //   print(st); 
  // }


  //  ##for in loop with Map

  // var add = {'name':'Ayush','city':'Rajkot','state': 'Gujrat','contry':'india'};
  // for(var key in add.keys)
  // {
  //   print(key);
  // }

  // for(var val in add.values)
  // {
  //   print(val);
  // }


  // ##forEach Loop with list

  // var lst = ["Raj","Deep","Sahil","Vansh","Ayush"];
  // lst.forEach((value) => print(value));


   // ##forEach Loop with Set

  // var student = {'raj','hddj','skla','maskj'};
  // student.forEach((value) => print(value));


  // ##forEach Loop with Map

  // var add = {'name':'Ayush','city':'Rajkot','state': 'Gujrat','contry':'india'};
  // add.forEach((key,value) => print('$key = $value'));


  //  ##print value or name with index;

  // var lst = ["Raj","Deep","Sahil","Vansh","Ayush"];
  // lst.asMap().forEach((i,value) => print('$i - $value'));


  // ##Switch


  // var command = 'open';

  // switch(command)
  // {
  //   case 'closed':
  //   print('complaint Ticket closed');
  //   break;

  //   case 'pending':
  //   print('complaint Ticket pending');
  //   break;

  //   case 'denied':
  //   print('complaint Ticket denied');
  //   break;

  //   case 'open':
  //   print('complaint Ticket open');
  //   break;

  //   default:
  //   print('Invalid complaint Ticket');

  // }

 }