//   ##5

void main()
{
  // ## Map Literal

  // var add = {'name':'Ayush','city':'Rajkot','state': 'Gujrat','contry':'india'};
  // print(add);
  // print(add.runtimeType);

  //Map<String,String> adr={......}; also valid.

  // var result={'Ayush':28,'Deep':35,'Raj':22,'Sahil':'32'};
  // print(result);
  // print(result.runtimeType);

  //  ##Empty Map
  //  ##Map() Constructor

  // var adr=Map();
  // print(adr);
  // print(adr.runtimeType);

  // // ##add item

  // adr['Raj']='Priya';
  // adr['Sahil']='Riya';
  // adr['ronak']='Rinkal';
  // adr['Rahul']='Pooja';
  // print(adr);

  // //  ## acces Map element

  // print(adr['Raj']);
  // print(adr['Rahul']);

  // // ## Map property and methods

  // print(adr.keys);
  // print(adr.values);
  // print(adr.containsKey('Raj'));
  // print(adr.containsValue
  // ("Riya"));
  // print(adr.containsKey('raj'));
  // print(adr.containsValue("riya"));

} 